import cv2, os
img = cv2.imread(os.path.join(".", "inputs", "1) dragon.jpg"))
img_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
cv2.namedWindow("BGR Dragon", cv2.WINDOW_NORMAL)
cv2.imshow("BGR Dragon", img)
cv2.waitKey(0)
cv2.namedWindow("RGB Dragon", cv2.WINDOW_NORMAL)
cv2.imshow("RGB Dragon", img_rgb)
cv2.waitKey(0)
cv2.namedWindow("Gray Dragon", cv2.WINDOW_NORMAL)
cv2.imshow("Gray Dragon", img_gray)
cv2.waitKey(0)
cv2.namedWindow("HSV Dragon", cv2.WINDOW_NORMAL)
cv2.imshow("HSV Dragon", img_hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()
cv2.imwrite(os.path.join(".", "outputs", "2) dragon_rgb.jpg"), img_rgb)
cv2.imwrite(os.path.join(".", "outputs", "3) dragon_gray.jpg"), img_gray)
cv2.imwrite(os.path.join(".", "outputs", "4) dragon_hsv.jpg"), img_hsv)